name: Deploy Vite to S3 (Dev)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to S3
    runs-on: ubuntu-22.04

    env:
      AWS_REGION: ap-northeast-2
      S3_BUCKET: modie-fe-prod
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PROD }}
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Vite App
        run: yarn build

      - name: Deploy to S3 (Overwrite)
        run: aws s3 sync dist/ s3://$S3_BUCKET --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID_PROD --paths "/*"
